export const SET_USERS ="SET_USERS";
export const GET_ERRORS ="GET_ERRORS";
export const GETUSER_PROFILE="GETUSER_PROFILE";
export const USERPROFILE_LOADING="USERPROFILE_LOADING";
export const TokenSetToUser="TokenSetToUser";
export const RemoveElemets="RemoveElemets";
export const UserVerfication ="UserVerfication";
export const UserProducts = "UserProducts";
export const getUserProducts = "getUserProducts";
export const getAllProducts = "getAllProducts";
export const GetByIdProducts = "GetByIdProducts";
export const ADDTOCARTITEMSS = "AddtoCartItems";
export const GETALLPRODUCTS = "GETALLPRODUCTS";
export const GETCARTPRODUCTS = "GETCARTPRODUCTS";
export const REMOVECARTPRODUCT = "REMOVECARTPRODUCT";
export const FAVOURITPRODUCTBYID="FAVOURITPRODUCTBYID";
export const MAPLOCATIONS ="MAPLOCATIONS";
export const SEARCGPRODUCT="SEARCGPRODUCT"
export const setChatData='setChatData';
export const addNewMessage="addNewMessage"
export const addNewRoom="addNewRoom"
export const markMessagesAsReaded="markMessagesAsReaded"
export const GETORDERS="GETORDERS"
export const BUYERORDERSDATA="BuyerDataORDERS"